[server.listener."http"]
bind = "[::]:8080"
protocol = "http"
tls.implicit = false

[storage]
data = "rocksdb"
fts = "rocksdb"
blob = "rocksdb"
lookup = "rocksdb"
directory = "internal"

[store."rocksdb"]
type = "rocksdb"
path = "/opt/stalwart/data"
compression = "lz4"

[directory."internal"]
type = "internal"
store = "rocksdb"

[tracer."log"]
ansi = false
enable = false
level = "info"
path = "/opt/stalwart/logs"
prefix = "stalwart.log"
rotate = "daily"
type = "log"

[tracer."console"]
type = "console"
level = "info"
ansi = true
enable = true
multiline = true

[authentication.fallback-admin]
user = "admin"
secret = "$6$c4lBN2l371PnpoUE$zsbsd6pUOqdnav659KaTHeSumXbnFf3i70H9gvhxHSsp8iMb6TeWhAYGiRCnWit4/SYxnrfsfVbt/H9Skf.t./"
